export default function PrivacyPage() {
  return (
    <main className="max-w-4xl mx-auto px-4 py-12 space-y-6">
      <h1 className="text-3xl font-bold">Privacy Policy</h1>

      <div className="prose prose-invert max-w-none space-y-6">
        <p className="text-slate-300">
          Last updated: January 4, 2026
        </p>

        <section>
          <h2 className="text-xl font-semibold mb-3">Information We Collect</h2>
          <p className="text-slate-300">
            We collect minimal information to provide our anonymous chat service:
          </p>
          <ul className="list-disc list-inside text-slate-300 space-y-1 mt-2">
            <li>Anonymous user IDs generated by Supabase</li>
            <li>Chat messages and voice recordings (temporarily stored)</li>
            <li>Interest preferences for matching</li>
            <li>Language and age group selections</li>
            <li>Technical data (IP addresses, device info) for security</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">How We Use Your Information</h2>
          <p className="text-slate-300">
            Your data is used solely to:
          </p>
          <ul className="list-disc list-inside text-slate-300 space-y-1 mt-2">
            <li>Facilitate anonymous chat matching</li>
            <li>Provide and improve our services</li>
            <li>Prevent abuse and ensure safety</li>
            <li>Comply with legal obligations</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Data Retention</h2>
          <p className="text-slate-300">
            Chat messages are automatically deleted after 24 hours. Voice messages are deleted after 7 days.
            Anonymous user data is retained only as long as necessary for service operation.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Your Rights</h2>
          <p className="text-slate-300">
            As an anonymous service, we don't store personal information that can be used to identify you.
            You can stop using the service at any time.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-3">Contact Us</h2>
          <p className="text-slate-300">
            For privacy concerns, contact us at support@inkhaven.in
          </p>
        </section>
      </div>
    </main>
  )
}